apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jeffs-weather-app
  region: us-east-1

vpc:
  id: vpc-09f523384cf3a8db6
  subnets:
    private:
      us-east-1a:
        id: subnet-0141fdb82eeda0abb
      us-east-1b:
        id: subnet-072445e848fb97210
      us-east-1c:
        id: subnet-0f4cad38ad9f2af5f
      us-east-1d:
        id: subnet-0dbf25de13253ec51

nodeGroups:
  - name: weather-app-workers
    instanceType: t3.small
    desiredCapacity: 4
    minSize: 3
    maxSize: 6
    privateNetworking: true
    ssh:
      allow: true  # Enable SSH access to the nodes
      publicKeyName: nova_one_kp

