apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server-container
        image: 767397836288.dkr.ecr.us-east-1.amazonaws.com/weather_repo:web-${{ github.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
