name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-service:latest ./api-service
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker-service:latest ./worker-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-service:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker-service:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name jeffs-weather-app-dev

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/api-service api-service=${{ secrets.DOCKERHUB_USERNAME }}/api-service:latest
        kubectl set image deployment/worker-service worker-service=${{ secrets.DOCKERHUB_USERNAME }}/worker-service:latest

    - name: Wait for deployment to complete
      run: kubectl rollout status deployment/api-service && kubectl rollout status deployment/worker-service
